### ISSUE TITLE
Symbol Composition

### ISSUE THREAD

**Issue by grathad** [grathad/GBlason#27]
# Description

Advanced support for Charges that are symbol with human keyword for their subparts.
Those keywords can't be listed exhaustively, outside of scanning the entire dictionary.
Those keywords need to be detected as not being necessarily a new charge, but a property of the previous charge

Simple Example `AZURE A LION RAMPANT BARRY OF TEN ARGENT AND GULES, ARMED OR`

The Symbol `A LION`
- Has an attitude `RAMPANT` which is detected as such
- It has a tincture (variation of the field) `BARRY OF TEN ARGENT AND GULES`
- And then a property, with its own tincture after a separator `, ARMED OR`. This is the part that needs detection and handling, with all the potential scenario that can be imagined. If an exhaustive list can be created for the most common symbols, it will not be possible for all.

The scope of this story is to document the most common part of the most common symbols.
Then to propose a dynamic detection without an exhaustive list of terms, for other symbols (through wildcard grammar if possible)

---
# Requirements

* Document the most common symbol properties
* Document the different cases, exceptions and their corresponding grammar
* Document a design to handle non common symbols

---
# Tasks

* [x] Document common symbols
* [x] Document common symbols sub parts
* [x] Document common symbols subparts grammar
* [x] Propose a design and document it for non common symbol subparts detection (grammar would be ideal)
