### ISSUE TITLE
Parse Comments

### ISSUE THREAD

**Issue by grathad** [grathad/GBlason#31]
# Description

Support comments in the blazon and ignore them (with still keeping them from the source)
Make the start and ending of a comment configurable (can depend on the language of input, and could be re used)

> Since the potential position of a comment is "anywhere" the grammar will no be the best place to handle this, unless it is part of the centralized implementation of the caller

---
# Requirements

* For all blazon that can be interpreted successfully, adding any comments `(any text between parenthesis)` will yield the same result as before

---
# Tasks

* [ ] Research grammar practices for comment handling
* [ ] Design the solution in the existing grammar
* [ ] Implementation
* [ ] Integration Test to validate that all working grammar still work with comments
* [ ] Merge
