### ISSUE TITLE
Advanced Divisions

### ISSUE THREAD

**Issue by grathad** [grathad/GBlason#32]
# Description

Add support for edge cases and advanced cases of division
**Will likely need to be split per grammar rules / cases later**

* Quarterly in quarterly, with support of coma rather than only semi colon to separate 2 quarters
* Complex multi-divisions that end up in different numbers of sub parts like 
`Per two pallets and per fess`
* Division with an ordinary as the separation
`Quartered by a cross Argent fimbriated Gules,`
* Division with the fields and the charges defined in 2 different groupes
`Quarterly per pale and per chevron Argent and Gules`

---
# Requirements

* Add support in the grammar for quarter ending with a simple coma
* Add support and integration validation for quarters in quarters
* Add support for complex multi divisions with multiple "per"
* Add support for division with a separator that is an object itself
* Add support for strange content grammar

---
# Tasks

* [ ] Research
* [ ] Design
* [ ] Implementation
 * [ ] Add support in the grammar for quarter ending with a simple coma
 * [ ] Add support and integration validation for quarters in quarters
 * [ ] Add support for complex multi divisions with multiple "per"
 * [ ] Add support for division with a separator that is an object itself
 * [ ] Add support for refactored and multi target grammars
* [ ] Test
* [ ] Review
* [ ] Merge
