### ISSUE TITLE
Complex Charges Detection

### ISSUE THREAD

**Issue by grathad** [grathad/GBlason#35]
# Description

Add the grammar definition support to be capable of detecting complex charges.
Complex charges are including multiple charges that have a specific link between each other (either a list or charges, a relative position, etc ...)

This ticket is massive, and might have to be broken down

---
# Requirements

All the complex charges listed in the repository are valid after parsing

### Field Variations

* [x] Field Variation Semy: `GULES BILLETY OR`
* [x] Field Variation Semy charge: `OR A SEMY OF HEARTS GULES`
* [x] Field Variation Semy charge plus charge on the field: `OR A SEMY OF HEARTS GULES A LION RAMPANT AZURE`
* [x] Field Variation on a symbol with subpart: `AZURE A LION RAMPANT BARRY OF TEN ARGENT AND GULES, ARMED OR`

### Symbol subparts

* [x] Simple Subpart: `ARGENT A LION GULES ARMED AND LANGUED OR`
* [x] Multiple Subpart Group: `ARGENT A LION RAMPANT PURPURE CROWNED OR, LANGUED AND ARMED GULES`

### Charge / Simple Charge / Single Simple Charge

* [x] Simple charge with all simple rules: `ARGENT A LION RAMPANT SABLE ARMED AND LANGUED GULES`
* [x] Simple Single Ordinary: `CHEQUY OR AND AZURE, A QUARTER ERMINE`
* [x] Simple Single Symbol: `AZURE, THE MOON ARGENT`

###  Charge / Simple Charge / Plural Simple Charge

* [x] Simple plural symbols: `OR, THREE HAMADES GULES`
* [x] Simple plural ordinaries: `OR, THREE PALLETS GULES`
* [x] Simple plural ordinaries: `Sable, two bars engrailed`

#### Charges Between

* [x] Between at the start: `ARGENT, BETWEEN TWO CHEVRONS SABLE THREE ASHEN KEYS VERT`
* [x] Between in the middle: `OR, A CROSS BETWEEN FOUR KEYS GULES`
* [x] 2 Between one on the other: `GULES, ON A BEND ARGENT BETWEEN TWO FOUNTAINS PROPER, A ROSE GULES BETWEEN TWO MULLETS SABLE`
* [x] Between + And: `ARGENT, A CHEVRON BETWEEN TWO CINQUEFOILS IN CHIEF GULES AND A SALTIRE AZURE IN BASE`
* [x] Between + Surmounted: `ARGENT, A LION GULES AND BETWEEN TWO CRESCENT SABLE IN CHIEF A CROSS GULES SURMOUNTED BY A MULLET OF THE FIELD`
* [x] Between + Charged: `OR, A FESS SABLE BETWEEN THREE ESCUTCHEONS GULES EACH CHARGED WITH A BEND VAIR`

## Documentation / Grammar
[Charge Group.pdf](https://github.com/grathad/GBlason/files/5724946/Charge.Group.pdf)
[Grammar.pdf](https://github.com/grathad/GBlason/files/5725418/Grammar.pdf)

## Out of scope

All the symbols and extended capabilities of symbol detection are out of scope
Issuant, demi-charge, location (thus charge list grammar)

---
# Tasks

* [x] List all the known cases of multiple charges and their relations
* [x] Design a grammar in English that can parse all those cases
* [x] Implementation of the complex charge grammar
  * [x] Field Variation Semy / Semy Charge
  * [x] Symbol / Subparts
  * [x] Charge / Simple Charge / Single Simple Charge
  * [x] Charge / Simple Charge / Plural Simple Charge
* [x] Validate that all the complex charges examples in the repository are parsed
* [x] Update the documentation (grammar docx) with the example used and passing
* [ ] Merge

**Comment by grathad** [comment]
Discovered an incompatible grammar rule, on the symbol level, since the symbol is a charge element, and the charge element tries to parse the tincture, but does not try to parse the symbol sub part.
Redefined all the symbol and symbol subpart grammar (https://github.com/grathad/GBlason/pull/37/commits/37d51d08418f2f2771c412e3e5816163a9a68c3e) as well as the parent simple charge to fix it (this part still in progress)

**Comment by grathad** [comment]
While doing the between start as the first complex charge grammar, the outcome for the simplest variant is buggy:
`OR A SEMY OF HEARTS GULES A LION RAMPANT AZURE` double the charge (same valid detection though) in the final result

![image](https://user-images.githubusercontent.com/1131865/103489802-f0a29080-4de4-11eb-83ec-1d1b183208a5.png)

**Comment by grathad** [comment]
Still not working but also not in the scope would be composed symbol names (like demi-lion) not parsing as of the current grammar. Issuant is also an issue for now
