### ISSUE TITLE
Grammar Tree View UI V1

### ISSUE THREAD

**Issue by grathad** [grathad/GBlason#55]
### Requirements

Complete the UI enhancement of the tree viewer to be useful in displaying and debugging the EBNF grammar

1. [x] Display lines between parent and child node #56 
  1.1 If there is only one child the line should be vertical (optimization should have removed all cases like this though)
  1.2 If there is more than one child, the first and last line should be rounded
  1.3 The line should be hidden when the node is collapsed, and displayed when it is expanded
2. [x] Tooltips for all the icons and text (complete text, and status for icons) #57 
  2.1 Finger print icon should display the GUID in the tooltip
  2.2 The name text area should display the full name in the tooltip (without ellipsis)
  2.3 The Rules text area should display the full rule in the tooltip (without ellipsis)
  2.4 Every icon should display the meaning if they are true and nothing if false 
3. [x] Add light and/or dark stroke to the nodes #56
4. [x] Support to collapse and expand all #58
  4.1 Change the icon to collapse all for a - icon (or multiple minuses?)
  4.2 Change the icon to expand for a + icon (or multiple pluses?)
  4.3 On collapse all, reduce all the tree so that only the head become visible
  4.4 ~~On the expand all start to expand all nodes including requesting their children one at a time following a left first tree exploration algorythm until a leaf or a reference is found~~ (linked to the reference node support requirement to identify them server side) 
5. [x] Support for Zoom and fit to screen #59 
  5.1 Change the icon for a fit all zoom one
  5.2 On click find the current total size of the drawing in the main group, then zoom it out so that all the content fit the screen, with a maximum to be defined.
  5.3 ~~Add a button to zoom and center to head, with a new icon, and reset the zoom to 1:1 and center to the head (horizontally and vertically)~~
  5.4 Make sure that the zoomed version still support drag and drop as well as the move to head function
  5.5 Add a manual zoom (like ctrl + wheel and num up / down) that enable to manually zoom to different level, should be compatible with the zoom to fit and return to 1:1 button
6. [ ] Support Node Reference
  6.1 Make sure the server return the proper reference information about the nodes (optimized ones) and that the client save that info
  6.2 When a reference is received client side, change the display so that it is accented and change the expand icon to be a link to the original node
  6.3 When the link to the original node is clicked, pan to it, if not available, add an endpoint to the server to return all the real node parents, so that the client know from where to auto expand, then auto expand, then pan to the real node
  6.4 Implement the expand all to use the reference and auto loading capability to close on requirement nb 4
7. [ ] Add a loading icon when expanding through a web request and remove it on completion of the request
